spring:
  application:
    name: auth-service
#db
  datasource:
    url: jdbc:postgresql://localhost:5434/api_db
    password: Davit123
    username: David
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/rest-api
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

#jpa
  ssl:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

keycloak:
  server-url: http://localhost:8080
  realm: rest-api
  client-id: oauth-admin-client
  client-secret: 59adTLMPCAnew2UnwRcxYKKwbhCqgEsN
#  minio
minio:
  url: http://localhost:9000
  access-name: admin
  access-secret: admin123
  bucket-name: mini-project
#  server
server:
  port: 8081
#jbxs dcqr hpja nguj