spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/rest-api
eureka:
  instance:
    prefer-ip-address: true
keycloak:
  server-url: http://localhost:8080