spring:
  config:
    import: optional:file:.env[.properties],optional:file:auth-service-spring-mini-project-group-03/.env[.properties]
  application:
    name: auth-service
#db
  datasource:
    url: jdbc:postgresql://localhost:5434/api_db
    password: Davit123
    username: David
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/realms/rest-api
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

#jpa
  ssl:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

keycloak:
  server-url: http://localhost:8080
  realm: rest-api
  client-id: oauth-admin-client
  client-secret: 59adTLMPCAnew2UnwRcxYKKwbhCqgEsN
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
#  minio
minio:
  url: http://localhost:9000
  access-name: admin
  access-secret: admin123
  bucket-name: mini-project
#  server
server:
  port: 8082
bakong:
  account-id: ${BAKONG_ACCOUNT_ID:}
  base-url: ${BAKONG_BASE_URL:https://api-bakong.nbc.gov.kh}
  email: ${EMAIL:}
onesignal:
  app-id: ${ONESIGNAL_APP_ID:}
  rest-api-key: ${ONESIGNAL_REST_API_KEY:}
#jbxs dcqr hpja nguj